##############################################
# Spring Boot - develop Configuration
##############################################
sicatel:
   authorities: 0
   resttemplate:
      timeout: 5000
   authorization:
      endpoint: http://localhost:9090/sicatel-authentication-api/v1/auth/validate-token